### ISSUE TITLE
Don't use strings for error notifications

### ISSUE THREAD

**Issue by TheBeardedQuack** [eminfedar/async-sockets-cpp#12]
The current implementation uses hard-coded strings for the error notifications, and they're not even accessible outside the scope.

This makes it's impossible to correctly capture all errors from the library without searching through the source for all the strings. It also makes comparison slower if you need to check for multiple error conditions compared to using something like an enum error code and a switch statement. Personally I'd propagate critical errors as exceptions in C++ but an error code would also be just fine.

**Comment by eminfedar** [comment]
onError function has `errorCode` and `errorMessage` string.

`errorCode` has value of the [errno.h](http://www.virtsync.com/c-error-codes-include-errno) errors. So you can use these "enums"  to detect error type.

like:
```cpp
tcpServer.Bind(8888, [](int errorCode, string errorMessage) {
    if (errorCode == EADDRINUSE)
        cerr << "Error, address in use.\n";
});
```

**Comment by TheBeardedQuack** [comment]
My bad, I have no idea how I completely missed that.
