### ISSUE TITLE
Installation under debian

### ISSUE THREAD

**Issue by HeisenbergK** [eminfedar/async-sockets-cpp#13]
Hello, is there a quick way to install in Debian so I can use globally on all my projects?
Thank you

**Comment by eminfedar** [comment]
1. Run `make` in `easysocket/` folder
2. Run `sudo install.sh` in 'easysocket/' folder to install library system-wide
3. Done!

Then you can link library with `-leasysocket`

**Comment by HeisenbergK** [comment]
Hello,

I tried that. I got no errors but when I compile, I get this:

`heisenbergk@HeisenbergK-OMEN:~$ g++ -leasysocket tryeasysock.cpp`
`tryeasysock.cpp:4:10: fatal error: tcpserver.h: No such file or directory`
` #include <tcpserver.h>`
`          ^~~~~~~~~~~~~`
`compilation terminated.`

In the tryeasysock.cpp I have the tcp-server example.

**Comment by eminfedar** [comment]
You should write like this: `<easysocket/tcpserver.h>`

Because header files are in `/usr/local/include/easysocket` folder.

**Comment by HeisenbergK** [comment]
Yes. That's true. It now works on g++ compiling. Still though can't find a way to make it work with cmake.

Any ideas?

**Comment by HeisenbergK** [comment]
That's great!!

I also used `link_libraries( pthread easysocket )` in CMake to finish the deal.

Thank you
