### ISSUE TITLE
TCP server stops receiving packets after around 160 seconds 

### ISSUE THREAD

**Issue by roboticanyair** [eminfedar/async-sockets-cpp#17]
Hi. 
I'm using the tcp-server example.
after around 160 seconds the server stop receiving packets, without any warning or error.
when I rerun the program the server receives then packets again for 160 seconds and so on.

I'v checked it a few times and it happens in my code as well as in the example.

**Comment by eminfedar** [comment]
Can you try again with new timeout fix commit? I haven't managed to reproduce this error. Maybe it has same problem with timeout issue.

**Comment by roboticanyair** [comment]
It looks like the problem is solved.
thanks a lot!
