### ISSUE TITLE
Thread-based -> libuv's Event-Based transfering.

### ISSUE THREAD

**Issue by eminfedar** [eminfedar/async-sockets-cpp#2]
Rewrite the whole background of the code with libuv is my priority from now.

Threads are hard to manage, consuming RAM too much when client size increased.

After this, the library will be lightweight and fully single-threaded asynchronous in real.

**Comment by TheBeardedQuack** [comment]
Threads aren't hard to manage, it's all about the patterns you use to make things easier.

Also it appears that libuv aims to achieve a similar goal as this library. For the purposes of learning I don't think implementing libuv will be as useful as attempting to implement your desired features from the ground up (this project isn't too complicated so in this case reinventing the wheel isn't too bad). Is this project mostly for your own education or something else?

**Comment by eminfedar** [comment]
Actually I wrote it because I need a simple abstraction between me and ugly,  complicated and hard to manage c++ socket libraries.

Threads can be managed yes, but, it is really holding your left ear with your right hand (not efficent way) :)

For example if 1000 new tcp connections established, 1000 new threads will be created and that will use too much ram and will be an overweight for the OS.

For example node.js adds only ~6-7MB of ram after 1000 connections. But our thread approach with 1000 threads adds ~40-45MB of Ram usage.(on windows even much more than that)

With blocking sockets, the only way running each of them in a seperate thread, but this is expensive.

Other non expensive solution is using non-blocking sockets and libuv managed it very nicely.

Yes, we could reinvent the wheel again but will it be much more better or just a waste of time? :)

If we can implement libuv's lightweightness and asynchronousity with C++'s power and simple library usage,  that will be a nice reinvention, actually I think too many users will join to us with a system like that.

What do you think? Won't be better if we merge the simpleness of nodejs and power of pure C++?

I think we should turn our face towards to that idea so it will be a better thing :)

**Comment by reductor** [comment]
> For example node.js adds only ~6-7MB of ram after 1000 connections. But our thread approach with 1000 threads adds ~40-45MB of Ram usage.(on windows even much more than that)

I feel like this is the wrong metric to watch when those numbers are insignificant compared to the number of clients, you might get reduced fragmentation but thats making assumptions about what those numbers represent.

Have you looked at boost.asio?

**Comment by eminfedar** [comment]
Why none of you guys like libuv? :) is there a significant difference between boost.asio and libuv? I think there is not.

If you are telling to me "boost.asio already does what you are trying to do"

I would like to say: "Not only boost.asio, there are also other libraries too, libuv does the same thing too, libevent, libev ..."

The point is not reinventing the "asynchronous i/o & sockets" from zero.

I've told the purpose of this repo early:

> I need a simple abstraction between me and ugly, complicated and hard to manage c++ socket libraries.

Does boost.asio is ugly too? Yes to me. If it doesn't for you, why are you caring about this repo then, just use the boost.asio :)

Also, I don't agree with you about telling these datas "wrong metric to watch". It is obvious. Who wants a thousand processes in his server's OS? I don't. Because I've tried and it is not good surely.

**Comment by TheBeardedQuack** [comment]
At first glance boost asio appears to actually be somewhat similar to the way NodeJS runs with the callbacks on event, though I've only had a very quick glance over it.

As for the metrics, I do agree with ReDucTor that 40-50MB for 1000 clients isn't really an issue, or at the very least not on its own. With the threading model you may be able to get those clients connected and disconnected quicker than with a single thread event model. While yes it may use more RAM for the same number of clients, it could end up always having less active clients if it is able to process the requests quicker.

The metric to be looking for is probably (connection time * number of connections) / RAM. Or something along those lines, it's not an "obvious" metric to measure the performance of a server and it depends on what is more important to you. Whether it's speed, stability, resource utilisation, etc. You design your metric to capture what matters for the project.

**Comment by eminfedar** [comment]
Hmm. I am thinking now... You guys loved the thread-based system, I loved libuv based system.

So we have two ways:
1) libuv based
2) thread based

I personally want to continue on libuv based but you guys loved and other people can love the thread-based system, so we can continue on it too.

So, here is the idea I have:
- Make **this** repository just **thread-based.**
- Make **another** repository for same foreground but **libuv-based**.

How about then? Maybe we can have both of them in the same library with folders?
```cpp
// For ones who wants to use thread based system:
#include <easysocket/threadbased/tcpserver.h>

// For ones who wants to use single-threaded libuv based system:
#include <easysocket/libuvbased/tcpserver.h>
```
Something like this?

Or maybe different names?
easysocket for this one,
asyncsockets for libuv one?

What do you think? I have decided to not transfer this repo to libuv, but we can continue with both.

**Comment by eminfedar** [comment]
Okay, this repository is thread based. I won't change it.

New libuv-based sockets are in a seperate repository now: https://github.com/eminfedar/simple-libuv-sockets
