### ISSUE TITLE
client crashed when server is closed

### ISSUE THREAD

**Issue by roboticanyair** [eminfedar/async-sockets-cpp#24]
Hi and thanks again for this great library.
i'm in the latest commit and noticed that when the server program is closed.

![image](https://user-images.githubusercontent.com/30431254/154916423-177406c7-2ced-4093-a52d-2dc572001f16.png)

this wasn't happening in earlier versions.

**Comment by eminfedar** [comment]
Related to this commit: fd075b9b3f907d74841f5b3591ea97aa246295d3

Will fix.

**Comment by eminfedar** [comment]
Fixed with this commit, can you confirm?:

a17b3e157fba5d97f57c7b42f2d3e72de24d4a10
