### ISSUE TITLE
Data race

### ISSUE THREAD

**Issue by ArdxWe** [eminfedar/async-sockets-cpp#25]
https://github.com/eminfedar/async-sockets-cpp/blob/a17b3e157fba5d97f57c7b42f2d3e72de24d4a10/async-sockets/include/tcpserver.hpp#L67

For listen thread, we are reading it, but in the main thread, we may close it and write to it.

Maybe we should use mutex or atomic bool instead.

**Comment by ChristianGabs** [comment]
Any direction on how implementation should look like ?

**Comment by eminfedar** [comment]
used `std::atomic<bool>`. Fixed in [fb72473](https://github.com/eminfedar/async-sockets-cpp/commit/fb72473e7f5ec38006107d924c248a17370ca7bd)
