### ISSUE TITLE
std::function is performance killer.

### ISSUE THREAD

**Issue by eminfedar** [eminfedar/async-sockets-cpp#6]
Should make a version without it.

**Comment by TheBeardedQuack** [comment]
Do you have proof of this? You should measure performance metrics before optimising.

**Comment by eminfedar** [comment]
For example:
Here is the two equal functions:
```cpp
int i = 0;
std::function<void()> a = [&] {
    i++;
};

auto b = [&]{
    i++;
};
```

Then if I run them in a 1 million for loop like this:
```cpp
int k;
for (k = 0; k < 1000000; k++){
    a();
    // b();
}
```

And measure the time with `time ./a.out` command results:
```
# Compiled with a() (std::function)
eminfedar@mi:~/Documents/C/functiontest$ time ./a.out 

real    0m0.052s
user    0m0.052s
sys     0m0.001s
eminfedar@mi:~/Documents/C/functiontest$ time ./a.out 

real    0m0.030s
user    0m0.029s
sys     0m0.001s
eminfedar@mi:~/Documents/C/functiontest$ time ./a.out 

real    0m0.051s
user    0m0.051s
sys     0m0.001s

# Compile again with other b(); (normal lamda function)
eminfedar@mi:~/Documents/C/functiontest$ g++ main.cpp -std=c++11
eminfedar@mi:~/Documents/C/functiontest$ time ./a.out 

real    0m0.015s
user    0m0.011s
sys     0m0.004s
eminfedar@mi:~/Documents/C/functiontest$ time ./a.out 

real    0m0.009s
user    0m0.004s
sys     0m0.005s
eminfedar@mi:~/Documents/C/functiontest$ time ./a.out 

real    0m0.008s
user    0m0.004s
sys     0m0.004s
```

It seems 4-5 times slower.

**Comment by TheBeardedQuack** [comment]
That isn't a fair test as you're effectively just calling a function directly when you're just using the lambda.
std::function has a layer of indirection, which is required if you want to be able to pass functions around and store them, a better test would be to compare against using an old style function pointer.

Also despite performance costs it's worth considering whether it's worth it verses the ease of use. std::function is incredibly easy to use for the caller and allows any callable object, not just functions to be passed in. If you were to use a function pointer then there's more problems you have to guard against and you lose a lot of flexibility. You could add that flexibility back in but why bother building numerous overloads and such when std::function provides the mechanisms for you.


Kind regards,
Ben Fisher

________________________________

**Comment by eminfedar** [comment]
Yes actually std::function is very easy to use. But I'm just considering can we make this better while not making ugly. I have tried template Functor once but it didn't work as expected as you said. Lot of flexibility gone.

Of course it is not changing for now.

But if I find a better way ... :)

**Comment by Not-Nik** [comment]
As TheBeardedQuack pointed out, your test isn't really proving anything in regards to execution speed. `std::function` indeed slows down the startup of a function, simply because there is at least one additional function call involved compared to a normal function, but the actual execution time of a function stays the same. That being said, on your given system the performs cost of using `std::function` is more or less always the same 20 - 40 ms, and won't increase with the complexity of the called function.

**Comment by eminfedar** [comment]
Think about it. you are developing a game server for example with this udp library and you want to have least latency. Think about it on thousands of users sending kilobytes of data and of course your handling function is not "i++".

I'm thinking about "max performance, least latency", because we are using C++, so: "performance" :)

Yes actualy function execution time doesn't change. I'm considering about latency here.

**Comment by Not-Nik** [comment]
Fair point and of course: your library, your call, but still; we got a decrease of average 30 ms per 1 million calls. That's `0.00003` milliseconds per call, so really nothing you should worry about.

**Comment by eminfedar** [comment]
It is open source and of course I can be wrong no problem :) (that's the point of the open source, a community which powers the other's lacks)

Actually you guys have convinced me using std::function is not a "big performance killer".

Having this type of flexibility while having only just a few amount of performance drop is a fair exchange :)
