### ISSUE TITLE
How about using google test framework to add unit tests?

### ISSUE THREAD

**Issue by wangqingjia1999** [eminfedar/async-sockets-cpp#8]
I'm currently reinventing the wheel of a simple HTTP server on my own. I've found it quite easy and convenient to use [google-test-framework](https://github.com/google/googletest) to add unit tests. I'm new to this field so this is just my narrow view. Anyway, this my naive recommendation :).

**Comment by TheBeardedQuack** [comment]
My two cents, I've enjoyed using Catch2 for C++ unit tests. Not really tried any others as it was the first I came across but I've not found a need yet to have to look for something else.

**Comment by wangqingjia1999** [comment]
😀 Glad to receive your reply, I'll simply close the issue :^)

**Comment by TheBeardedQuack** [comment]
You can still leave this open? Adding unit tests is a good idea, no matter what framework it's using.
I was just providing more options for repo author.
