### ISSUE TITLE
tcpserver close and exit, run it again is show 98 : Cannot bind the socket.

### ISSUE THREAD

**Issue by danyver2000** [eminfedar/async-sockets-cpp#9]
First, my client connect tcpserver.
Second,  tcpserver  close and exit, then run it again and it shows "98 : Cannot bind the socket".

I check network list, it always keep TIME_WAIT status.

How should I do ?

netstat -nat  | grep 8888

tcp        0      0 127.0.0.1:8888          127.0.0.1:54422         TIME_WAIT

**Comment by eminfedar** [comment]
This is why it is happening, when the server is closed properly it is not happening. But you are right, I should add it again: https://github.com/eminfedar/async-sockets-cpp/commit/12a14b96c6824d1e2f572c33debbdfa2ed90372d

**Comment by eminfedar** [comment]
Here is the fix. You can try now, it should work:
https://github.com/eminfedar/async-sockets-cpp/commit/39e76ba6625ef4ab4e7da45d85c05bc429181706

**Comment by danyver2000** [comment]
Yes, it can work.
Thank you for all your assistance.

**Comment by danyver2000** [comment]
Yes, it can work.
Thank you for all your assistance.
